# Generated by Django 6.0.6 on 2026-09-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_telegramcontact_blocked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(blank=True, db_index=True, max_length=100)),
                ("medium", models.CharField(blank=True, max_length=100)),
                (
                    "campaign",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("content", models.CharField(blank=True, max_length=100)),
                ("term", models.CharField(blank=True, max_length=100)),
                ("landing_path", models.CharField(blank=True, max_length=200)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisition",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("source", models.CharField(blank=True, db_index=True, max_length=100)),
                ("medium", models.CharField(blank=True, max_length=100)),
                (
                    "campaign",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("content", models.CharField(blank=True, max_length=100)),
                ("term", models.CharField(blank=True, max_length=100)),
                ("landing_path", models.CharField(blank=True, max_length=200)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_hits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "created_at"],
                        name="users_campa_campaig_387e7f_idx",
                    )
                ],
            },
        ),
    ]
