# Generated by Django 6.0.6 on 2026-09-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0016_quizanswer_selected_choices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Icon tint family: emerald/sky/violet/indigo (brand), amber/rose (accent), slate (neutral)",
                max_length=20,
            ),
        ),
    ]
